# Generated by Django 4.0.4 on 2022-05-20 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='artigo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Rascunho'), (1, 'Publicado')], default=0),
        ),
        migrations.AddField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
