# Generated by Django 4.0.4 on 2022-05-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_artigo_categoria_artigo_imagem_alter_artigo_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(null=True, upload_to='blog/', verbose_name='Imagem'),
        ),
    ]
