# Generated by Django 4.0.4 on 2022-05-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colaboracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome completo do colaborador', max_length=100, null=True, verbose_name='Nome completo')),
                ('telefone', models.IntegerField(blank=True, help_text='Número de telefone do colaborador. Apenas números', null=True, verbose_name='Telefone')),
                ('descricao', models.TextField(blank=True, help_text='Descreva como pode colaborar', null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Colaborações',
            },
        ),
        migrations.CreateModel(
            name='doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome completo do doador', max_length=100, null=True, verbose_name='Nome completo')),
                ('telefone', models.IntegerField(blank=True, help_text='Número de telefone do doador. Apenas números', null=True, verbose_name='Telefone')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do tipo de ajuda a disponibilizar', null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Doações',
            },
        ),
        migrations.CreateModel(
            name='solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(blank=True, help_text='Nome completo de quem submete a solicitação doador', max_length=100, null=True, verbose_name='Nome completo')),
                ('telefone_autor', models.IntegerField(blank=True, help_text='Número de telefone do doador. Apenas números', null=True, verbose_name='Telefone')),
                ('nome_necessitado', models.CharField(blank=True, help_text='Nome completo da pessoa necessitada', max_length=100, null=True, verbose_name='Nome completo da pessoa necessitada')),
                ('telefone_necessitado', models.IntegerField(blank=True, help_text='Número de telefone da pessoa necessitada. Apenas números', null=True, verbose_name='Telefone da pessoa necessitada')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do tipo de ajuda a disponibilizar', null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
